---
# File: vhost_del.yml
# Part: Apache
#
# Description: Delete a virtual host
#
# Parameters:
# - $vhost : virtualhost name

 - name: Disable Virtualhost entry | Remove Symlink
   command: /usr/local/bin/disable-site {{ vhost }}

 - name: Apache | Virtualhost delete | Remove virtual host file
   file: path=/etc/httpd/sites-available/{{ vhost }}.conf state=absent

 - name: Apache restart
   command: sudo /etc/init.d/httpd restart
