---

# THESIS DEPLOYMENT
# ===========================

- name: Thesis
  hosts: all
#  user: asrun
#  max_fail_percentage: 0

  tasks:
# 01. Define Iptables --------------------------------------------------------------------------------------------
  - name: Define Iptables
    command: echo hello world!

# 02. Delete CRX objects -----------------------------------------------------------------------------------------
  - name: Delete CRX Mappings
    command: echo hello world!

  - name: Delete CRX Dev Mappings
    command: echo hello world!

  - name: Delete CRX Int Mappings
    command: echo hello world!

  - name: Delete CRX Mappings Global
    command: echo hello world!

  - name: Delete CRX Mappings Launcher 
    command: echo hello world!

  - name: Delete CRX Mappings Models
    command: echo hello world!

# 03. Remove Folder on Server -----------------------------------------------------------------------------------
  - name: Remove Jjamardo folder
    command: echo hello world!

  - name: Remove Impl folder
    command: echo hello world!

# 04. Remove old CQ packages ------------------------------------------------------------------------------------
  - name: Remove old all-components package
    command: echo hello world!

  - name: Remove old jjamardo-components package
    command: echo hello world!

# 05. Copy new packages to /opt/cq/tmp/ -----------------------------------------------------------------------
  - name: Copy new all-components.zip
    command: echo hello world!

  - name: Copy new jjamardo-components.zip
    command: echo hello world!

# 06. Upload new packages into CRX ------------------------------------------------------------------------------
  - name: Upload the new all-components.zip on Publisher
    command: echo hello world!

  - name: Upload the new jjamardo-components.zip on Publisher
    command: echo hello world!

# 07. Install new packages ---------------------------------------------------------------------------------------
  - name: Install all-components.zip on Publisher
    command: echo hello world!

  - name: Install new jjamardo-components.zip on Publisher
    command: echo hello world!

# 08. Final Tasks (delete jsps, CQ stop, delete dispatcher cache, CQ start) --------------------------------------
  - name: Delete precompiled jsps on Publisher
    command: echo hello world!

  - name: Clean Dispatcher Cache on Publisher
    command: echo hello world!

  - name: make sure CQ is stopped
    command:  echo hello world!

  - name: Pause for 2 minutes
    pause: minutes=1

  - name: make sure CQ is started
    command:  echo hello world!

# 09. Automatic SOA Testing ----------------------------------------------------------------------------------------------------
#tbd

# 10. Remove Iptables 
  - name: Define Iptables
    command:  echo hello world!
